#!/usr/bin/env bash
# Define variables
KEY_NAME="school"
BITS=4096

# Generate RSA key pair
ssh-keygen -t rsa -b $BITS -f ~/.ssh/$KEY_NAME 

echo "RSA key pair generated: $KEY_NAME (private) and $KEY_NAME.pub (public)"
