#!/usr/bin/env bash

# Define variables
KEY_NAME="school"
PASSPHRASE="betty"
BITS=4096

# Generate RSA key pair
ssh-keygen -t rsa -b $BITS -f $KEY_NAME -N "$PASSPHRASE"

echo "RSA key pair generated: $KEY_NAME (private) and $KEY_NAME.pub (public)"
