#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server
# Configure it to use round-robin algorithm to distribute requests

set -e  # Exit on error

# Variables
# STUDENT_ID="your_student_id"
WEB1="3.86.234.74"
WEB2="3.93.147.156"

# Update package lists
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null

# Create a backup of the original config file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original

# Configure HAProxy
sudo bash -c "cat > /etc/haproxy/haproxy.cfg << EOF
global
    log 127.0.0.1 local0 notice
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    timeout connect  5000
    timeout client  10000
    timeout server  10000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 $WEB1:80 check
    server web-02 $WEB2:80 check
EOF"

# Restart HAProxy service
sudo service haproxy restart

# Check HAProxy status
sudo systemctl status haproxy

