#!/usr/bin/env bash
#  a Bash script that transfers a file from our client to a server:
if (($# < 4)); then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
    exit 1;
fi
scp -o "stricthostkeychecking no" -i $4 -r $1 "$3@$2:~/"
